tests:
  - name: Check if insert_books.js exists
    setup: npm install mongodb
    run: test -f insert_books.js
    input: ""
    output: ""
    comparison: included
    timeout: 10
    points: 10

  - name: Check if queries.js exists
    run: test -f queries.js
    input: ""
    output: ""
    comparison: included
    timeout: 10
    points: 10

  - name: Set up MongoDB
    run: |
      wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
      echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
      sudo apt-get update
      sudo apt-get install -y mongodb-org
      sudo systemctl start mongod
      sudo systemctl status mongod
    input: ""
    output: "active"
    comparison: included
    timeout: 60
    points: 10

  - name: Run insert_books.js
    setup: npm install mongodb
    run: |
      sudo systemctl status mongod | grep "active"  # Verify MongoDB is running
      node insert_books.js
    input: ""
    output: "books were successfully inserted into the database"
    comparison: included
    timeout: 20
    points: 20

  - name: Check basic query in queries.js
    setup: npm install mongodb
    run: grep -q "find({" queries.js && grep -q "genre:" queries.js
    input: ""
    output: ""
    comparison: included
    timeout: 10
    points: 15

  - name: Check advanced query in queries.js
    setup: npm install mongodb
    run: grep -q "\$gt" queries.js && grep -q "\$and" queries.js
    input: ""
    output: ""
    comparison: included
    timeout: 10
    points: 15

  - name: Check aggregation pipeline in queries.js
    setup: npm install mongodb
    run: grep -q "aggregate" queries.js && grep -q "\$group" queries.js
    input: ""
    output: ""
    comparison: included
    timeout: 10
    points: 15

  - name: Check indexing in queries.js
    setup: npm install mongodb
    run: grep -q "createIndex" queries.js && grep -q "explain" queries.js
    input: ""
    output: ""
    comparison: included
    timeout: 10
    points: 15